### ISSUE TITLE
Netherrite Axes don't work

### ISSUE THREAD

**Issue by Kleberstoff** [SourceWriters/SmoothTimber#10]
After downloading and editing the config.yml and adding the netherrite axe manually i've found that it doens't work with SM.

What I did,

Downloaded and installed SM
Edited config.yml (see below)
Restarted Server
toggled sm
and try to break oak tree

it works with all axes except netherrite

 
<details><summary>config.yml</summary>

```yml
version: 2
cutter:
  radius: 2
  materials:
  - WOODEN_AXE
  - STONE_AXE
  - IRON_AXE
  - GOLDEN_AXE
  - DIAMOND_AXE
  - NETHERRITE_AXE
options:
  cutter:
    sneak: false
    toggleable: true
    permissions: false
    sync-detection: false
enchantments:
  unbreaking:
    enabled: true
  fortune:
    enabled: false
    multiplier: 1.0
exclusion:
  enabled: false
  list: []
worlds:
  enabled: false
  blacklist: false
  list:
  - world
  - world_nether
  - world_the_end
extensions:
  blockylog: true
```
</details>

Youtube Video of it: https://youtu.be/Uo-L_Wtv8ck
