### ISSUE TITLE
[BUG]: Plugin fails to load on Folia.

### ISSUE THREAD

**Issue by pmnlla** [SourceWriters/SmoothTimber#72]
### Describe what happend

The latest version of the plugin, `smoothtimber-legacy-1.24.7.jar` fails to load on Folia. It doesn't bring down the server. There is zero output to the players and truncated error logs on stdout. This is on an aarch64 Rocky Linux server.
After having changed the server to paper software, the plugins runs well.

### Reproduction steps

1. Configure folia server in Docker Compose. This is my service:
```yml
    minecraft:
        image: 'itzg/minecraft-server'
        tty: true
        stdin_open: true
        ports:
            - '25565:25565'
        environment:
            EULA: "TRUE"
            TYPE: "FOLIA"
        volumes:
            - /home/rocky/mcserver-data:/data
```
2. Start the server: `docker compose <-f when applicable> up -d minecraft`
3. Power off the server: `docker compose down minecraft`
4. Add plugin to plugins directory (in the compose, it is /home/rocky/mcserver-data/plugins/smoothtimber.jar)
5. Launch the server
6. Plugin fails to load.

### Expected behavior

The plugin would work without a hitch and be accessible to all with its permissions.

### Media

[mcserver.log](https://github.com/SourceWriters/SmoothTimber/files/12307445/mcserver.log)

### Java Version

Java 17

### Server Software

Folia

### Minecraft Version

1.20.1

### Plugin Version

2.14.7

### Additional Information

Please let me know if there is any more info necessary to debug this.
