### ISSUE TITLE
[BUG] crouch to chop and regular chop reversed

### ISSUE THREAD

**Issue by voigtman** [SourceWriters/SmoothTimber#9]
**Describe the bug**

After the plugin version 1.17 update crouch (sneak) to chop a tree and the regular chop a block behavior have reversed.
**To Reproduce**

_CONFIG..._
```
options:
  cutter:
    sync-detection: false
    permission:
      wood-type: false
      cutter-type: false
    sneak: 'on' 
```

**Expected behavior**

Whole tree should be coming down upon me blocky head...
Instead this happens when I hit the tree regular with my axe and when I sneak I only break a single block.

**Media**

**Server:**

 - Software: Paper
 - Server Version: 1.16.5 -release 778
 - Plugin Version: 1.17.1
 - Java Version: 16

**Additional context**

Just that the two functions, crouch to chop and regular chop have reversed.

**Comment by Lauriichan** [comment]
Please note that those options were moved to 

```
options:
  sneak: 'off'
  toggleable: 'off'
  sync-detection: false
  permission:
    wood-type: false
    cutter-type: false
```

just options.
